// <auto-generated />
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(MonstersContext))]
    [Migration("20220110085608_TestMigration")]
    partial class TestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DB.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AC")
                        .HasColumnType("int");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("int");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AC = 12,
                            AttackModifier = 5,
                            AttackPerRound = 1,
                            Damage = 12,
                            DamageModifier = 6,
                            HitPoints = 59,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 2,
                            AC = 11,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = 1,
                            DamageModifier = 1,
                            HitPoints = 32,
                            Name = "Ice Toad"
                        },
                        new
                        {
                            Id = 3,
                            AC = 17,
                            AttackModifier = 5,
                            AttackPerRound = 2,
                            Damage = 12,
                            DamageModifier = 2,
                            HitPoints = 161,
                            Name = "Elf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
