// <auto-generated />
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(MonstersContext))]
    [Migration("20220110021536_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DB.Monster", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AC")
                        .HasColumnType("int");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("int");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerRound")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("MinACtoAlwaysHit")
                        .HasColumnType("int");

                    b.Property<int>("Weapon")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Name = "Goblin",
                            AC = 2,
                            AttackModifier = 5,
                            AttackPerRound = 2,
                            Damage = 1,
                            DamageModifier = 1,
                            DamagePerRound = 6,
                            HitPoints = 50,
                            MinACtoAlwaysHit = 7,
                            Weapon = 1
                        },
                        new
                        {
                            Name = "Griffon",
                            AC = 2,
                            AttackModifier = 5,
                            AttackPerRound = 2,
                            Damage = 1,
                            DamageModifier = 1,
                            DamagePerRound = 6,
                            HitPoints = 50,
                            MinACtoAlwaysHit = 7,
                            Weapon = 1
                        },
                        new
                        {
                            Name = "Elf",
                            AC = 2,
                            AttackModifier = 5,
                            AttackPerRound = 2,
                            Damage = 1,
                            DamageModifier = 1,
                            DamagePerRound = 6,
                            HitPoints = 50,
                            MinACtoAlwaysHit = 7,
                            Weapon = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
